name: Deploy Docker Containers

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Passo 2: Configuração do SSH (adicionando chave SSH privada)
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # A chave privada armazenada em GitHub Secrets

      # Passo 3: Conectar ao servidor via SSH e executar o comando Docker
      - name: SSH to server and deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_SERVER }} << 'EOF'
            # Atualizar pacotes
            sudo apt-get update -y
            sudo apt-get upgrade -y

            # Ou usar docker-compose
            cd /opt/quizapp/
            docker-compose up --build -d

            # Fechar a sessão SSH
            exit
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

